INSERT INTO citta (id, nome, sigla) VALUES (1, 'Agrigento', 'AG');
INSERT INTO citta (id, nome, sigla) VALUES (2, 'Alessandria', 'AL');
INSERT INTO citta (id, nome, sigla) VALUES (3, 'Ancona', 'AN');
INSERT INTO citta (id, nome, sigla) VALUES (4, 'Aosta', 'AO');
INSERT INTO citta (id, nome, sigla) VALUES (5, 'Arezzo', 'AR');
INSERT INTO citta (id, nome, sigla) VALUES (6, 'Ascoli Piceno', 'AP');
INSERT INTO citta (id, nome, sigla) VALUES (7, 'Asti', 'AT');
INSERT INTO citta (id, nome, sigla) VALUES (8, 'Avellino', 'AV');
INSERT INTO citta (id, nome, sigla) VALUES (9, 'Bari', 'BA');
INSERT INTO citta (id, nome, sigla) VALUES (10, 'Barletta-Andria-Trani', 'BT');
INSERT INTO citta (id, nome, sigla) VALUES (11, 'Belluno', 'BL');
INSERT INTO citta (id, nome, sigla) VALUES (12, 'Benevento', 'BN');
INSERT INTO citta (id, nome, sigla) VALUES (13, 'Bergamo', 'BG');
INSERT INTO citta (id, nome, sigla) VALUES (14, 'Biella', 'BI');
INSERT INTO citta (id, nome, sigla) VALUES (15, 'Bologna', 'BO');
INSERT INTO citta (id, nome, sigla) VALUES (16, 'Bolzano', 'BZ');
INSERT INTO citta (id, nome, sigla) VALUES (17, 'Brescia', 'BS');
INSERT INTO citta (id, nome, sigla) VALUES (18, 'Brindisi', 'BR');
INSERT INTO citta (id, nome, sigla) VALUES (19, 'Cagliari', 'CA');
INSERT INTO citta (id, nome, sigla) VALUES (20, 'Caltanissetta', 'CL');
INSERT INTO citta (id, nome, sigla) VALUES (21, 'Campobasso', 'CB');
INSERT INTO citta (id, nome, sigla) VALUES (22, 'Caserta', 'CE');
INSERT INTO citta (id, nome, sigla) VALUES (23, 'Catania', 'CT');
INSERT INTO citta (id, nome, sigla) VALUES (24, 'Catanzaro', 'CZ');
INSERT INTO citta (id, nome, sigla) VALUES (25, 'Chieti', 'CH');
INSERT INTO citta (id, nome, sigla) VALUES (26, 'Como', 'CO');
INSERT INTO citta (id, nome, sigla) VALUES (27, 'Cosenza', 'CS');
INSERT INTO citta (id, nome, sigla) VALUES (28, 'Cremona', 'CR');
INSERT INTO citta (id, nome, sigla) VALUES (29, 'Crotone', 'KR');
INSERT INTO citta (id, nome, sigla) VALUES (30, 'Cuneo', 'CN');
INSERT INTO citta (id, nome, sigla) VALUES (31, 'Enna', 'EN');
INSERT INTO citta (id, nome, sigla) VALUES (32, 'Fermo', 'FM');
INSERT INTO citta (id, nome, sigla) VALUES (33, 'Ferrara', 'FE');
INSERT INTO citta (id, nome, sigla) VALUES (34, 'Firenze', 'FI');
INSERT INTO citta (id, nome, sigla) VALUES (35, 'Foggia', 'FG');
INSERT INTO citta (id, nome, sigla) VALUES (36, 'Forlì-Cesena', 'FC');
INSERT INTO citta (id, nome, sigla) VALUES (37, 'Frosinone', 'FR');
INSERT INTO citta (id, nome, sigla) VALUES (38, 'Genova', 'GE');
INSERT INTO citta (id, nome, sigla) VALUES (39, 'Gorizia', 'GO');
INSERT INTO citta (id, nome, sigla) VALUES (40, 'Grosseto', 'GR');
INSERT INTO citta (id, nome, sigla) VALUES (41, 'Imperia', 'IM');
INSERT INTO citta (id, nome, sigla) VALUES (42, 'Isernia', 'IS');
INSERT INTO citta (id, nome, sigla) VALUES (43, 'La Spezia', 'SP');
INSERT INTO citta (id, nome, sigla) VALUES (44, 'Latina', 'LT');
INSERT INTO citta (id, nome, sigla) VALUES (45, 'Lecce', 'LE');
INSERT INTO citta (id, nome, sigla) VALUES (46, 'Lecco', 'LC');
INSERT INTO citta (id, nome, sigla) VALUES (47, 'Livorno', 'LI');
INSERT INTO citta (id, nome, sigla) VALUES (48, 'Lodi', 'LO');
INSERT INTO citta (id, nome, sigla) VALUES (49, 'Lucca', 'LU');
INSERT INTO citta (id, nome, sigla) VALUES (50, 'Macerata', 'MC');
INSERT INTO citta (id, nome, sigla) VALUES (51, 'Mantova', 'MN');
INSERT INTO citta (id, nome, sigla) VALUES (52, 'Massa-Carrara', 'MS');
INSERT INTO citta (id, nome, sigla) VALUES (53, 'Matera', 'MT');
INSERT INTO citta (id, nome, sigla) VALUES (54, 'Messina', 'ME');
INSERT INTO citta (id, nome, sigla) VALUES (55, 'Milano', 'MI');
INSERT INTO citta (id, nome, sigla) VALUES (56, 'Modena', 'MO');
INSERT INTO citta (id, nome, sigla) VALUES (57, 'Monza e della Brianza', 'MB');
INSERT INTO citta (id, nome, sigla) VALUES (58, 'Napoli', 'NA');
INSERT INTO citta (id, nome, sigla) VALUES (59, 'Novara', 'NO');
INSERT INTO citta (id, nome, sigla) VALUES (60, 'Nuoro', 'NU');
INSERT INTO citta (id, nome, sigla) VALUES (61, 'Oristano', 'OR');
INSERT INTO citta (id, nome, sigla) VALUES (62, 'Padova', 'PD');
INSERT INTO citta (id, nome, sigla) VALUES (63, 'Palermo', 'PA');
INSERT INTO citta (id, nome, sigla) VALUES (64, 'Parma', 'PR');
INSERT INTO citta (id, nome, sigla) VALUES (65, 'Pavia', 'PV');
INSERT INTO citta (id, nome, sigla) VALUES (66, 'Perugia', 'PG');
INSERT INTO citta (id, nome, sigla) VALUES (67, 'Pesaro e Urbino', 'PU');
INSERT INTO citta (id, nome, sigla) VALUES (68, 'Pescara', 'PE');
INSERT INTO citta (id, nome, sigla) VALUES (69, 'Piacenza', 'PC');
INSERT INTO citta (id, nome, sigla) VALUES (70, 'Pisa', 'PI');
INSERT INTO citta (id, nome, sigla) VALUES (71, 'Pistoia', 'PT');
INSERT INTO citta (id, nome, sigla) VALUES (72, 'Pordenone', 'PN');
INSERT INTO citta (id, nome, sigla) VALUES (73, 'Potenza', 'PZ');
INSERT INTO citta (id, nome, sigla) VALUES (74, 'Prato', 'PO');
INSERT INTO citta (id, nome, sigla) VALUES (75, 'Ragusa', 'RG');
INSERT INTO citta (id, nome, sigla) VALUES (76, 'Reggio Calabria', 'RC');
INSERT INTO citta (id, nome, sigla) VALUES (77, 'Reggio Emilia', 'RE');
INSERT INTO citta (id, nome, sigla) VALUES (78, 'Rieti', 'RI');
INSERT INTO citta (id, nome, sigla) VALUES (79, 'Rimini', 'RN');
INSERT INTO citta (id, nome, sigla) VALUES (80, 'Roma', 'RM');
INSERT INTO citta (id, nome, sigla) VALUES (81, 'Rovigo', 'RO');
INSERT INTO citta (id, nome, sigla) VALUES (82, 'Salerno', 'SA');
INSERT INTO citta (id, nome, sigla) VALUES (83, 'Sassari', 'SS');
INSERT INTO citta (id, nome, sigla) VALUES (84, 'Savona', 'SV');
INSERT INTO citta (id, nome, sigla) VALUES (85, 'Siena', 'SI');
INSERT INTO citta (id, nome, sigla) VALUES (86, 'Siracusa', 'SR');
INSERT INTO citta (id, nome, sigla) VALUES (87, 'Sondrio', 'SO');
INSERT INTO citta (id, nome, sigla) VALUES (88, 'Taranto', 'TA');
INSERT INTO citta (id, nome, sigla) VALUES (89, 'Teramo', 'TE');
INSERT INTO citta (id, nome, sigla) VALUES (90, 'Terni', 'TR');
INSERT INTO citta (id, nome, sigla) VALUES (91, 'Trapani', 'TP');
INSERT INTO citta (id, nome, sigla) VALUES (92, 'Trento', 'TN');
INSERT INTO citta (id, nome, sigla) VALUES (93, 'Treviso', 'TV');
INSERT INTO citta (id, nome, sigla) VALUES (94, 'Trieste', 'TS');
INSERT INTO citta (id, nome, sigla) VALUES (95, 'Udine', 'UD');
INSERT INTO citta (id, nome, sigla) VALUES (96, 'Varese', 'VA');
INSERT INTO citta (id, nome, sigla) VALUES (97, 'Venezia', 'VE');
INSERT INTO citta (id, nome, sigla) VALUES (98, 'Verbano-Cusio-Ossola', 'VB');
INSERT INTO citta (id, nome, sigla) VALUES (99, 'Vercelli', 'VC');
INSERT INTO citta (id, nome, sigla) VALUES (100, 'Verona', 'VR');
INSERT INTO citta (id, nome, sigla) VALUES (101, 'Vibo Valentia', 'VV');
INSERT INTO citta (id, nome, sigla) VALUES (102, 'Vicenza', 'VI');
INSERT INTO citta (id, nome, sigla) VALUES (103, 'Viterbo', 'VT');


INSERT INTO sport (id, nome,immagine) VALUES (1,'Calcio a otto','sport_calcio_8.jpg');
INSERT INTO sport (id, nome,immagine) VALUES (2,'Calcetto','sport_calcio_5.jpg');
INSERT INTO sport (id, nome,immagine) VALUES (3,'Tennis','sport_tennis.jpg');
INSERT INTO sport (id, nome,immagine) VALUES (4,'Pallavolo','sport_pallavolo.jpeg');
INSERT INTO sport (id, nome,immagine) VALUES (5,'Basket','sport_basket.png');
INSERT INTO sport (id, nome,immagine) VALUES (6,'Padel','sport_padel.jpeg');
INSERT INTO sport (id, nome,immagine) VALUES (7,'Badminton','sport_badminton.jpeg');
INSERT INTO sport (id, nome,immagine) VALUES (8,'Rugby a sette','sport_rugby.jpeg');
INSERT INTO sport (id, nome,immagine) VALUES (9,'Beach Volley','sport_beachVolley.jpeg');
INSERT INTO sport (id, nome,immagine) VALUES (10,'Hockey su prato','sport_hockeySuPrato.jpeg');







INSERT INTO users (id, name, surname, email, eta,citta_id) VALUES (100, 'Mario', 'Rossi', 'admin@example.com', 40,103);
INSERT INTO credentials (id, username, password, role, user_id) VALUES (200, 'adm', '$2a$12$s3QTUipQcQAOXN0aZ0scie6KFTZ9ISeU6nnIUmeeXwgrL4AsnJ4.u', 'ROLE_ADMIN', 100);
INSERT INTO users (id, name, surname, email, eta,citta_id) VALUES (101, 'Giulia', 'Bianchi', 'user@example.com', 28,103);
INSERT INTO credentials (id, username, password, role, user_id) VALUES (201, 'ute', '$2a$12$x/pn.th/advauZHiRKICZer7ObgOzLpyOwZdZ4GrrOaaGKgS4yeee', 'ROLE_USER', 101);
INSERT INTO users (id, name, surname, email,eta,citta_id) VALUES (10, 'Biagou', 'Wanyou', 'biagou.02@gmail.com', 29,103);
INSERT INTO credentials (id, username, password, role, user_id) VALUES (202, 'biagou', '$2a$10$qanOsKUT3qHAzpL71RpE1e.E21mT9P3XAOzTiT9fs8dDXG1lwHSo.', 'ROLE_ADMIN', 10);

